name: Build Wextra APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Kodlari indir
        uses: actions/checkout@v4

      - name: Java 17 kur
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Gradle izinlerini ver
        run: chmod +x gradlew

      - name: Debug APK olustur
        run: ./gradlew assembleDebug

      - name: APK yukle
        uses: actions/upload-artifact@v4
        with:
          name: Wextra-APK
          path: app/build/outputs/apk/debug/app-debug.apk
