name: Android APK'sı oluşturun

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları indir
        uses: actions/checkout@v4

      - name: Java 17 kur
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Gradle kur
        uses: gradle/actions/setup-gradle@v4

      - name: Debug APK oluştur
        run: gradle assembleDebug

      - name: APK yükle
        uses: actions/upload-artifact@v4
        with:
          name: Wextra-APK
          path: app/build/outputs/apk/debug/app-debug.apk
