name: Build wextra APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Repository indiriliyor
        uses: actions/checkout@v4

      - name: Java 17 kuruluyor
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: ZIP dosyası açılıyor
        run: |
          unzip wextra.zip -d project

      - name: Proje klasörünü bul
        run: |
          echo "Dosyalar:"
          find project -maxdepth 3 -type f | head -50

      - name: Gradle ile APK oluştur
        working-directory: project/wextra
        run: |
          gradle assembleDebug

      - name: APK yükle
        uses: actions/upload-artifact@v4
        with:
          name: wextra-APK
          path: project/wextra/app/build/outputs/apk/debug/app-debug.apk
